### ISSUE TITLE
Question: Is the current version of the plugin compatible with sonarqube 9.9 LTS?

### ISSUE THREAD

**Issue by dgokcin** [mc1arke/sonarqube-community-branch-plugin#734]
Helloo 

First off, thanks for the action. We have been using this action for a very long time 👍 

I wanted to ask if the current version of the plugin is compatible with the 9.9 LTS version of SonarQube? Depending on its compatibility, we might update our sonarqube server to 9.9!

Thanks!

**Comment by mc1arke** [comment]
Simple answer: I've not got round to checking this yet, so don't know.

**Comment by iSergio** [comment]
Hello
With 1.14.0 started and worked... But now Java 17 minimum required....
`/lib/jvm/java-11/bin/java -Xms512m -Xmx2048m -Djava.net.preferIPv4Stack=true -jar /opt/sonarqube/current/lib/sonar-application.jar
Error: LinkageError occurred while loading main class org.sonar.application.App
        java.lang.UnsupportedClassVersionError: org/sonar/application/App has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

**Comment by dgokcin** [comment]
cool, so I will follow here seeing that some people started to see problems.

**Comment by MCMicS** [comment]
I updated my first SonaQube instance today to 9.9 and it seems that all is working with Plugin version 1.14.0

**Comment by josesimon** [comment]
Can someone confirm if branch comparison against master works properly?

![image](https://user-images.githubusercontent.com/12864857/217859559-7b96a6e0-19af-4f8d-92aa-661638608a18.png)

Seems that is not detecting new code
This was working to me for sonar 9.7

**Comment by xuhuisheng** [comment]
I tried sonarqube-community-branch-plugin-1.14.0 with sonarqube-9.9, both of branch and gitlab MergeRequest decorate just fine.

Thanks author great jobs. :laughing:

**Comment by LocalHeroPro** [comment]
Don't work on Java 11, 19.
Works on Java 17.

**Comment by Xeyos88** [comment]
Using the docker image from version 9.9 instead, it again reports the error` Error opening zipper file or JAR manifest missing : ./extensions/plugins/sonarqube-community-branch-plugin-1.14.0.jar`

**Comment by Mistic92** [comment]
I just migrated to 9.9 but when scanning I'm getting error
```
ERROR: Error during SonarScanner execution
java.lang.NoClassDefFoundError: org/sonar/scanner/scan/branch/ProjectPullRequestsLoader
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:555)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:904)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at com.github.mc1arke.sonarqube.plugin.CommunityBranchPlugin.define(CommunityBranchPlugin.java:170)
	at com.github.mc1arke.sonarqube.plugin.CommunityBranchPluginBootstrap.define(CommunityBranchPluginBootstrap.java:72)
	at org.sonar.scanner.bootstrap.ExtensionInstaller.install(ExtensionInstaller.java:57)
	at org.sonar.scanner.scan.SpringProjectScanContainer.addScannerExtensions(SpringProjectScanContainer.java:327)
	at org.sonar.scanner.scan.SpringProjectScanContainer.doBeforeStart(SpringProjectScanContainer.java:156)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:186)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:137)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:188)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:167)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:72)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:66)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:[126](https://gitlab.com/yosh-ai/yosh-platform/the-platform/-/jobs/3825509536#L126))
	at org.sonarsource.scanner.cli.Main.execute(Main.java:81)
	at org.sonarsource.scanner.cli.Main.main(Main.java:62)
Caused by: java.lang.ClassNotFoundException: org.sonar.scanner.scan.branch.ProjectPullRequestsLoader
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.net.FactoryURLClassLoader.loadClass(URLClassLoader.java:904)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
```

**Comment by MCMicS** [comment]
@Mistic92 HAs you changed the plugin version to `1.14.0`?

The class was remove with SonarQube 9.8. I recommend to use the last plguin and a newer sonar scanner. Then the scan should work without warning

**Comment by Mistic92** [comment]
@MCMicS that was the cause :) After update it is working. I'm getting other error but not related to plugin

**Comment by MCMicS** [comment]
@mc1arke I think this issue can be closed because it seems that the plugin works with SonarQube 9.9.

Or what do you think?

**Comment by lorirava** [comment]
> Using the docker image from version 9.9 instead, it again reports the error` Error opening zip file or JAR manifest missing : ./extensions/plugins/sonarqube-community-branch-plugin-1.14.0.jar`
> 
> UPDATE: seems to be working, some problem related to docker volumes

how did you solve that error? I got it in a kubernetes helm installation

**Comment by garsiv1932** [comment]
@lorirava i am havinfg the same problem and i dont understand whats happening, did you fixed it?

**Comment by lorirava** [comment]
First, I installed or updated sonarqube without a plugin. When it started correctly, I ran the helm chart again adding the plugin. And this worked

**Comment by garsiv1932** [comment]
My problem was the quotes, a partner on my job created the docker run with quotes, I don't know how it works for him. Its Working for me now.

**Comment by vinodhini-devops** [comment]
> In my case I do not use the related funcionality for PR analysis so the useful part of the plugin is the branch analysis
> 
> And it is working as expected :)

Is it developer version or community version of sonarqube 9.9

**Comment by brother** [comment]
Open a separate ticket about it and try to explain what settings you have (note that you need to specify plugin version in two separate places).

Maybe consider using the [docker image with the plugin integrated](https://hub.docker.com/r/mc1arke/sonarqube-with-community-branch-plugin) while you're at it.
