### ISSUE TITLE
Support to 10.8.1

### ISSUE THREAD

**Issue by eirisdg** [mc1arke/sonarqube-community-branch-plugin#1031]
**Describe the bug**
After upgrade to 10.8.1, the plugin doesn't work.

```
Caused by: java.lang.NoClassDefFoundError: org/sonar/db/measure/MeasureDto
```

In 2025.1.0 release the problem doesn't exists

**Comment by iZnoGod722** [comment]
Hey, I've upgraded our sonarqube community to 10.8.1 recently and did encounter the same issue as you, but that was be cause I was still using version 1.19.0 instead of the latest 1.23.0. After switching to the latest, it all worked.

Are you sure you are using the latest, 1.23.0, plugin version?

**Comment by mc1arke** [comment]
I'm not sure what you're referring to with 10.8.1 - there's no 10.8 community edition, so no patched version 10.8.1. I'm closing this as invalid since it doesn't sound right, and doesn't contain any meaningful replication steps, but am happy to reopen it if you provide the details that the bug report template requests.
