### ISSUE TITLE
Cannot load plugin for SonarQube 10.8

### ISSUE THREAD

**Issue by MCMicS** [mc1arke/sonarqube-community-branch-plugin#1011]
**Describe the bug**

**To Reproduce**
1. Update to SonarQube 10.8
2. SonarQube fails to start because missing class `org.sonar.db.measure.LiveMeasureDto`

**Expected behavior**

**Screenshots**

**Software Versions**
 - SonarQube Version: 10.8 (Docekr 24.12.0.100206-community)
 - Plugin Version: 1.22

**Stacktrace**
```
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@726e5805-com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.PullRequestWs': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@726e5805-com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@726e5805]
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:794)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:220)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1609)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1573)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1439)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1349)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:781)
        ... 21 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jdk.internal.loader.ClassLoaders$AppClassLoader@726e5805-com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction': Lookup method resolution failed; nested exception is java.lang.IllegalStateException: Failed to introspect Class [com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@726e5805]
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:298)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1302)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1219)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1609)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1573)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1439)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1349)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:904)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:781)
        ... 38 common frames omitted
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.github.mc1arke.sonarqube.plugin.server.pullrequest.ws.pullrequest.action.ListAction] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@726e5805]
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485)
        at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:276)
        ... 54 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/sonar/db/measure/LiveMeasureDto
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.base/java.lang.Class.getDeclaredMethods(Unknown Source)
        at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467)
        ... 56 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.sonar.db.measure.LiveMeasureDto
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 60 common frames omitted
```

**Comment by mc1arke** [comment]
Yes, it was removed in https://sonarsource.atlassian.net/browse/SONAR-22879. It should be a case of switching to Measures but I've not tested my change for this yet.

**Comment by muandane** [comment]
hello, so is there a fix for this in the deployment or does it require some code changes in the plugin ?

**Comment by mc1arke** [comment]
It will require code changes

**Comment by bernalvarela** [comment]
I have make the changes to make the plugin work on the 10.8 sonar version.

![image](https://github.com/user-attachments/assets/8ae7a5d4-f792-4f18-ad68-5d8cdbe7727a)

How can i contribute and upload my changes to be reviewed?

Regards

**Comment by mc1arke** [comment]
@bernalvarela You'd need to push your changes to a branch on your fork of the project and then raise a Pull Request to submit them to this project, however I've already raised #1013 to propose a fix for this. Please do take a look and add any comments if you think I've missed anything.

**Comment by bernalvarela** [comment]
Is more complete than mine, really good work!!.

Thanks for your time and your effort!!

**Comment by mc1arke** [comment]
Fix released in 1.23.0
