### PR TITLE
feat: UI addon to support SonarQube 25.4

### LINKED ISSUE #1049: v1.23 does not work with SonarQube 25.3.0.104237-community
**Describe the bug**
Plugin v1.23 does not work with SonarQube 25.3.0.104237-community (see also [comment](https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/1033#issuecomment-2701865187) on #1033) . No error is shown in the logs.
May be caused by massive code (and API?) changes in the SonarQube v25.2 -> v25.3 (see https://github.com/SonarSource/sonarqube/compare/25.2.0.102705...25.3.0.104237) and/or Plugin-API v11.1 -> v11.2 (see https://github.com/SonarSource/sonar-plugin-api/compare/11.1.0.2693...11.2.0.2797)  update

**To Reproduce**
Just use image (tag 25.3) provided by https://github.com/adrianmusante/docker-sonarqube/tree/main (https://github.com/adrianmusante/docker-sonarqube/tree/main). Plugin seems to be loaded correctly, see following excerpt from sonar.log:
```log
...
sonarqube-1  | 2025.03.10 08:14:32 INFO  web[][o.s.c.e.CoreExtensionsLoader] Loaded core extensions: Community Branch Plugin
sonarqube-1  | 2025.03.10 08:14:32 INFO  web[][o.s.s.p.LogServerVersion] SonarQube Server / 25.3.0.104237 / 7cc57fb683cea7b8fbdfc3965ab93ebfd2916c60
...
sonarqube-1  | 2025.03.10 08:14:33 INFO  web[][o.s.s.p.ServerPluginManager] Deploy Community Branch Plugin / 1.23.0 / null
...
sonarqube-1  | 2025.03.10 08:14:38 INFO  web[][o.s.s.p.p.PlatformLevelStartup] Running Community Edition
sonarqube-1  | 2025.03.10 08:14:38 INFO  web[][o.s.s.p.Platform] Web Server is operational
sonarqube-1  | 2025.03.10 08:14:38 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
sonarqube-1  | 2025.03.10 08:14:38 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[COMPUTE_ENGINE] from [/opt/bitnami/sonarqube]: /opt/bitnami/java/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/bitnam
i/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.nio=ALL-UNNAMED --add-
opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=java.management/sun.management=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -javaagent:/bitnami/sonarqu
be/extensions/plugins/sonarqube-community-branch-plugin.jar=ce -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-25.3.0.104237.jar:/opt/bitnami/sonarqube/lib/jdbc/postgresql/postgresql-42.7.5.jar org.sonar.ce.app.CeSe
rver /opt/bitnami/sonarqube/temp/sq-process17601094284425973468properties
sonarqube-1  | 08:14:38.720 [main] INFO com.github.mc1arke.sonarqube.plugin.CommunityBranchAgent -- Loading agent
...
sonarqube-1  | 2025.03.10 08:14:38 INFO  ce[][o.s.c.e.CoreExtensionsLoader] Loaded core extensions: Community Branch Plugin
...

```

- Analyzed project's branch selector (dropdown)  is no longer functional (see screenshot)
- Missing "Branches & Pull Requests" Project Settings Entry. Navigating to the corresponding settings page manually causes "The page you were looking for does not exist." to be shown (without any corresponding entry in the logs)

**Expected behavior**

- Analyzed branches selectable
- Branch analysis possible

**Screenshots**
Image

**Software Versions**
 - SonarQube Version: 25.3.0.104237-community
 - Plugin Version: 1.23

### LINKED ISSUE #1054: Compatibility with Sonarqube 2025.1 LTA
Hi @mc1arke ,

SonarQube has released its latest 2025.1 LTA version. You can check the release notes here: https://docs.sonarsource.com/sonarqube-server/latest/server-upgrade-and-maintenance/release-notes/.

Is there a plan to release a compatibility plugin for this version, or is the current plugin already compatible?

### PR DESCRIPTION
**Pull request by jackylamhk**
Pending #1057; closes #1049; closes #1054

This PR reimplements removed features from the SonarQube Community Build by overriding the full frontend build, as [no public APIs allow global injections](https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/1049#issuecomment-2885339497). Most code is refactored from [`SonarSource/sonarqube-webapp@2025.1.0.10869`](https://github.com/SonarSource/sonarqube-webapp/tree/2025.1.0.10869).

While this may break across versions as it uses an internal API (`libs/sq-server-addons/addons.branches`), it should keep this plugin alive for another major version or two.

### CODE REVIEW

**Comment by riteshkumar-prive** [comment]
Just to add.

We tested the PR changes with version **Community Build v25.5.0.107428** and the branch is not greyed out anymore 


image

**Comment by jackylamhk** [comment]
> UI indeed is functional again in Community Build 25.4 and 25.5, except for the project's new code page. Inside a project, go to `Project Settings > New Code` {F883DA38-506C-4CCE-B7B1-BC47ED664E19}
> 
> Firefox browser log
> 
> ```
> TypeError: i is undefined
>     a BranchListSection.tsx:54
>     React 2
>     PB BranchListSection.tsx:53
> ```
> 
> Chrome browser log
> 
> ```
> TypeError: Cannot read properties of undefined (reading 'filter')
>     at BranchListSection.tsx:54:37
>     at Object.useMemo (react-dom.production.min.js:177:189)
>     at ge.useMemo (react.production.min.js:26:48)
>     at PB (BranchListSection.tsx:53:22)
> ```
> 
> Dropdown and `Branches & Pull Requests` page are ok. We don't use DevOps integration, so this part of the UI we cannot validate.

It looks like I inadvertently re-implemented some logic that's already passed down to the component. Can you try again now?

**Comment by riteshkumar-prive** [comment]
We checked SonarQube with Github Qualty gate analysis checks; and it seems to work fine except already existing issue https://github.com/mc1arke/sonarqube-community-branch-plugin/issues/1043reported in

**Comment by moisesh18** [comment]
Hi! 
How can I download the jar of this branch?

**Comment by riteshkumar-prive** [comment]
@moisesh18 

I went to the respective fork => Actions Tab => clicked on latest action run on 25.4.0 branch => scrolled down on the summary to download the artifacts (both JAR and webapp)

Let me know if its helpful to you.

**Comment by panicking** [comment]
@jackylamhk Testing it, I found it ok, I need to remove some ai_link in newer version of sonarqube. I rebased and apply all the contribuition on top of sonarqube-25.5.0.107428

**Comment by panicking** [comment]
From my side with latest sonarqube:

Screenshot from 2025-06-03 11-54-46

Then I have tested jenkins pipeline with webhook
```
    'Sonarqube': {
      withSonarQubeEnv(credentialsId: 'amarula-sonar') {
        sh './gradlew sonar -Dsonar.pullrequest.key="${GERRIT_CHANGE_NUMBER}-${GERRIT_PATCHSET_NUMBER}" -Dsonar.pullrequest.base="${GERRIT_BRANCH}" -Dsonar.pullrequest.branch="${GERRIT_REFSPEC}"'
      }
    },
    'Quality Gate': {
      timeout(time: 1, unit: 'HOURS') {
        try {
          def qg = waitForQualityGate()
          if (qg.status != 'OK') {
            error "Pipeline aborted due to quality gate failure: ${qg.status}"
          }
        } finally {
          sonarToGerrit(
            inspectionConfig: [
              analysisStrategy: pullRequest()
            ]
          )
        }
      }
    },
```

Confirm that webhook is working

and comment to gerrit too

```
diff --git a/.env b/.env
index 782589d..8528cc9 100644
--- a/.env
+++ b/.env
@@ -1,5 +1,5 @@
 # The Sonarqube base image. 'latest' if building locally, '8.5-community' if targeting a specific version
-SONARQUBE_VERSION=25.4.0.105899-community
+SONARQUBE_VERSION=25.5.0.107428-community
 
 # The name of the Dockerfile to run. 'Dockerfile' is building locally, 'release.Dockerfile' if building the release image
 DOCKERFILE=Dockerfile
diff --git a/build.gradle b/build.gradle
index 9d9d2f0..934d517 100644
--- a/build.gradle
+++ b/build.gradle
@@ -40,7 +40,7 @@ repositories {
     }
 }
 
-def sonarqubeVersion = '25.4.0.105899'
+def sonarqubeVersion = '25.5.0.107428'
 def sonarqubeLibDir = "${projectDir}/sonarqube-lib"
 def sonarLibraries = "${sonarqubeLibDir}/sonarqube-${sonarqubeVersion}/lib"
 
diff --git a/sonarqube-webapp b/sonarqube-webapp

```

**Comment by jinu0007** [comment]
Any fix for 25.3 as this 1.24 plugin giving failed to instantiate  error

**Comment by SuhovDE** [comment]
Worked perfectly with 25.5.

After upgrade to 25.6 I got an error:

`ERROR: Error during SonarScanner execution
java.lang.NoClassDefFoundError: org/sonar/api/rules/ActiveRule
	at com.github.mc1arke.sonarqube.plugin.classloader.ProviderType$1.createFactory(ProviderType.java:31)
	at com.github.mc1arke.sonarqube.plugin.classloader.DefaultElevatedClassLoaderFactoryProvider.createFactory(DefaultElevatedClassLoaderFactoryProvider.java:36)
	at com.github.mc1arke.sonarqube.plugin.CommunityBranchPluginBootstrap.define(CommunityBranchPluginBootstrap.java:79)
	at org.sonar.scanner.bootstrap.ExtensionInstaller.installExtensionsForPlugins(ExtensionInstaller.java:64)
	at org.sonar.scanner.bootstrap.ExtensionInstaller.install(ExtensionInstaller.java:51)
	at org.sonar.scanner.bootstrap.SpringScannerContainer.addScannerExtensions(SpringScannerContainer.java:164)
	at org.sonar.scanner.bootstrap.SpringScannerContainer.doBeforeStart(SpringScannerContainer.java:156)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:225)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:206)
	at org.sonar.scanner.bootstrap.SpringGlobalContainer.doAfterStart(SpringGlobalContainer.java:142)
	at org.sonar.core.platform.SpringComponentContainer.startComponents(SpringComponentContainer.java:227)
	at org.sonar.core.platform.SpringComponentContainer.execute(SpringComponentContainer.java:206)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at jdk.proxy1/jdk.proxy1.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:[123](http://gitlab/Fiplan/messenger/-/jobs/867#L123))
	at org.sonarsource.scanner.cli.Main.execute(Main.java:78)
	at org.sonarsource.scanner.cli.Main.main(Main.java:59)
Caused by: java.lang.ClassNotFoundException: org.sonar.api.rules.ActiveRule
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:97)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:86)
	... 26 more`

**Comment by mc1arke** [comment]
@SuhovDE that error is due to the sonar-plugin-api having dropped that class. It's used by this plugin's classloader to find Sonarqube's core classloader, so will need a new class to be selected. Could you raise this as a new bug since it's a breaking change for 25.6 independent of the UI issues in other 25.x versions?

**Comment by mc1arke** [comment]
@jackylamhk Thanks for the comprehensive change! I've rebased your commits onto the tip of the master branch which is currently compatible with Sonarqube 25.4, dropped the previous 25.4 compatibility commits from your branch, and added an extra commit to guide users on installing the new web component directly and against a Helm chart. Please take a look and let me know if you disagree with any of my changes.

I plan on squashing your branch on merge since the change is really a single unit of work - let me know if you want to do that yourself prior to me merging.

**Comment by jackylamhk** [comment]
@mc1arke Great, thanks for the update. Just tested with the pre-release on a Helm install and confirmed this works with 25.5 too. Let me push the updates and it should be ready to merge.

My biggest concern is (CI) testing against new versions of the UI; I wonder if the build itself would be a sufficient indicator of whether there are any API changes. We can test it out with a PR for 25.6 later.

**Comment by panicking** [comment]
> @mc1arke Great, thanks for the update. Just tested with the pre-release on a Helm install and confirmed this works with 25.5 too. Let me push the updates and it should be ready to merge.
> 
> My biggest concern is (CI) testing against new versions of the UI; I wonder if the build itself would be a sufficient indicator of whether there are any API changes. We can test it out with a PR for 25.6 later.

Well was tested already before. I have sent the full way how I tested it

**Comment by jackylamhk** [comment]
> Well was tested already before. I have sent the full way how I tested it

Thanks, haha. I was referring to Helm specifically in this case.

**Comment by jackylamhk** [comment]
@mc1arke I see that you also made a change to support 25.6, do you want to update this PR or create one separately?

**Comment by mc1arke** [comment]
My change is backwards compatible to 25.4. Whilst I suspect most people will move to the latest version as I release it, I'd ideally want to release against 25.4, perform the upgrade to 25.5 and release that, then upgrade and release for 25.6 so I have reference commits for future release processes

**Comment by jackylamhk** [comment]
> My change is backwards compatible to 25.4. Whilst I suspect most people will move to the latest version as I release it, I'd ideally want to release against 25.4, perform the upgrade to 25.5 and release that, then upgrade and release for 25.6 so I have reference commits for future release processes

Sounds good, let me revert the commit.

**Comment by jackylamhk** [comment]
Should be good to merge for 25.4 now.

File: sonarqube-webapp-addons/setup.sh [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+EOF
+}
+
+function main() {
+    cd ./sonarqube-webapp
+    echo "Creating symlink for sonarqube-webapp/libs/sq-server-addons"
+    rm -rf ./libs/sq-server-addons
+    ln -s "${CURRENT_DIR}/sonarqube-webapp-addons" ./libs/sq-server-addons
+    override_vite_config
+}
```
[the remark this answers is not in the document]
Comment (mc1arke) [reply sonarqube-webapp-addons/setup.sh:28]: Thanks, that explains why I was getting different artefacts on different machines - I'd manually switched tags locally but the CI was using the value you'd committed.

**Comment by mc1arke** [comment]
Merged, thanks for the contribution. I'm going to check over the remaining issues and MRs to see what's fixable, then aim to get a release out that includes your changes.
